add token label support
brianleect/etherscan-labels pull request #14
Opened 2023-02-21 09:12 UTC by C0MM4ND

2023-02-22 19:46 UTC, brianleect commented
@C0MM4ND Thanks for the PR it looks good. Do you think you would be able to run the scraper and populate the token section as well?

2023-02-22 19:47 UTC, brianleect reviewed
^ Populate tokens

2023-02-23 03:14 UTC, C0MM4ND commented
Thanks for your review.

I've tested some of the account and token labels, but not all.
Crawling all labels requires my laptop continuously open for a relative long time, but I'm on a outdoor business trip during these days.
So let me convert this PR back to draft. I'll re-open after the new commit.

2023-02-26 21:51 UTC, brianleect requested changes
Thanks for the PR, everything looks good. Just need to address whether it makes sense to add token data for function combineAllJson()

2023-02-26 21:51 UTC, brianleect commented on main.py
>                      if address not in combinedJSON:
Any thoughts regarding the need to combine for tokens as well or just accounts being sufficient?

2023-02-27 15:20 UTC, brianleect approved these changes
Looks good!

2023-02-27 15:20 UTC, merged